### ISSUE TITLE
Create top-down guide for cirkit in documentation

### ISSUE THREAD

**Issue by andreasgrv** [april-tools/cirkit#304]
It would be nice to create a top-down guide, i.e. a landing page for newcomers to be able to navigate cirkit.

### Goals
* Provide high level vision of the library:  "Building efficient and trustworthy AI systems" - this can be added to banner.
* Explain what features are supported:  "Building probabilistic models, learning them and performing inference"
* Reduce friction for a user that wants to build a circuit

### TODOs
* [ ] Create a landing page in the docs, e.g. see [scikit-learn's](https://github.com/scikit-learn/scikit-learn/tree/main/doc). Three blocks can be "building", "learning" and "inference" for probabilistic circuits. Other potential boxes: "X is a circuit", "Cirkit integration with deep learning", "Neuro-symbolic AI".
* [ ] Link notebooks as examples for the blocks (see sklearn)
* [ ] Add a `getting started` section for newcomers to README.md pointing to the docs and notebooks. (currently only points to docs).

**Comment by loreloc** [comment]
Grid of cards
https://squidfunk.github.io/mkdocs-material/reference/grids/
